// Code generated by "stringer -type=Status"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Available-0]
	_ = x[Reserved-1]
	_ = x[Expired-2]
}

const _Status_name = "AvailableReservedExpired"

var _Status_index = [...]uint8{0, 9, 17, 24}

func (i Status) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Status_index)-1 {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[idx]:_Status_index[idx+1]]
}
